### ISSUE TITLE
django.db password authentication failed

### ISSUE THREAD

**Issue by John-Theo** [rafalp/misago_docker#91]
**Awesome awesome work, dude!** 
I have been looking for a descent python-based forum framework for a while, and this is it!

I was following the instructions on the [Misago Gitbook](https://misago.gitbook.io/docs/setup/misago).
**During `appctl setup` the following error occured:**
```
django.db.utils.OperationalError: FATAL:  password authentication failed for user "misago_OHvRk2HHqeDml1X0"
```
I'm working on a cloud server provided by [Alibaba Cloud](https://www.alibabacloud.com/) running Ubuntu 18.04 as root.
```
> uname -a
Linux Misago 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Have I done something wrong?

**Detailed information below:**
```
Migrating database
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "misago_bL998pqdYLBpjl8r"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 87, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "misago_bL998pqdYLBpjl8r"

Loading default avatar gallery
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "misago_bL998pqdYLBpjl8r"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/misago/users/management/commands/loadavatargallery.py", line 13, in handle
    for avatar in AvatarGallery.objects.all():
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "misago_bL998pqdYLBpjl8r"

Creating first superuser account
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "misago_bL998pqdYLBpjl8r"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/misago/users/management/commands/createsuperuser.py", line 73, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/misago/users/management/commands/createsuperuser.py", line 84, in handle
    settings = get_dynamic_settings()
  File "/usr/local/lib/python3.7/site-packages/misago/conf/shortcuts.py", line 6, in get_dynamic_settings
    cache_versions = get_cache_versions()
  File "/usr/local/lib/python3.7/site-packages/misago/cache/versions.py", line 7, in get_cache_versions
    return {i.cache: i.version for i in queryset}
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "misago_bL998pqdYLBpjl8r"
```

**Comment by rafalp** [comment]
Hi!

I've seen this error reported few times in the past, but I've never managed to reproduce it. Could you say if you've used `appctl` to configure your site, or you've tried `docker-compose up` before that?

If you have no other data on this server, I would just remove the directory you've cloned, clear docker with `docker system prune --volumes` and just try again.

**Comment by John-Theo** [comment]
Sorry for the delay, github did not show updates on this thread (don't know why, lol).

The cloud server mentioned above was just initialized before I used it. That is to say, it was a brand new system, **no user data, no custom packages, no nothing**. I installed `docker` and `docker-compose` using apt-get (maybe installed pip and other irrelevant stuff, can't be really specific), and jump right into `appctl setup`.

I can reproduce this error on my Mac **every time** running `appctl setup`.
And I destroy all docker containers (using `docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)`) before I run `appctl setup`.

I printed out the `POSTGRES_USER` and `POSTGRES_PASSWORD` value in `settings.py` and `.run`, and they all **works as expected**.
https://github.com/rafalp/misago_docker/blob/ae86de843d6b4f311ea227902af86a09f3f11a3f/misago/misagodocker/settings.py#L54-L55
https://github.com/rafalp/misago_docker/blob/ae86de843d6b4f311ea227902af86a09f3f11a3f/misago/.run#L25-L27

Also, even if the error mentioned in my last comment occurs, the pipeline still prints out something like "setup completed successfully", and if I ignore the error and run `docker-compose up`, the following lines occurs:
```
postgres_1            | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1            |
postgres_1            | 2020-01-30 20:11:26.853 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1            | 2020-01-30 20:11:26.853 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1            | 2020-01-30 20:11:26.858 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1            | 2020-01-30 20:11:26.896 UTC [27] LOG:  database system was shut down at 2020-01-30 19:56:24 UTC
postgres_1            | 2020-01-30 20:11:26.925 UTC [1] LOG:  database system is ready to accept connections
postgres_1            | 2020-01-30 20:11:40.565 UTC [34] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:11:40.565 UTC [34] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:11:42.615 UTC [35] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:11:42.615 UTC [35] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:11:44.664 UTC [36] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:11:44.664 UTC [36] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:11:46.713 UTC [37] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:11:46.713 UTC [37] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:11:48.759 UTC [38] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:11:48.759 UTC [38] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:11:50.816 UTC [39] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:11:50.816 UTC [39] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:11:52.873 UTC [40] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:11:52.873 UTC [40] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:11:54.930 UTC [41] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:11:54.930 UTC [41] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:11:56.981 UTC [42] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:11:56.981 UTC [42] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:11:59.033 UTC [43] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:11:59.033 UTC [43] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:12:01.091 UTC [44] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:12:01.091 UTC [44] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:12:02.802 UTC [45] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:12:02.802 UTC [45] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:12:04.185 UTC [46] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:12:04.185 UTC [46] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:12:05.584 UTC [47] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:12:05.584 UTC [47] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:22:15.335 UTC [58] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:22:15.335 UTC [58] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:22:17.396 UTC [59] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:22:17.396 UTC [59] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:22:19.453 UTC [60] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:22:19.453 UTC [60] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:22:21.503 UTC [61] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:22:21.503 UTC [61] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:22:23.554 UTC [62] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:22:23.554 UTC [62] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:22:25.612 UTC [63] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:22:25.612 UTC [63] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"

(...... some lines in the middle ......)

nginx-lets-encrypt_1  | Debugging tips: -v improves output verbosity. Help is available under --help.
nginx-lets-encrypt_1  | /app
nginx-lets-encrypt_1  | Sleep for 3600s
nginx-lets-encrypt_1  | 2020/01/30 20:22:15 Received event start for container e2a1b0430068
nginx-lets-encrypt_1  | 2020/01/30 20:22:26 Received event die for container e2a1b0430068
nginx-lets-encrypt_1  | 2020/01/30 20:22:41 Debounce minTimer fired
nginx-lets-encrypt_1  | 2020/01/30 20:22:41 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
postgres_1            | 2020-01-30 20:23:47.756 UTC [66] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:23:47.756 UTC [66] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1            | 2020-01-30 20:23:48.347 UTC [67] FATAL:  password authentication failed for user "misago"
postgres_1            | 2020-01-30 20:23:48.347 UTC [67] DETAIL:  Role "misago" does not exist.
postgres_1            | 	Connection matched pg_hba.conf line 95: "host all all all md5"
```

Interestingly, **things works fine in terms of the Misago repo**, the whole system starts smoothly. I'm still figuring out the difference.

**Comment by rafalp** [comment]
PostgreSQL container uses volume to preserve database data between images, so you need to also delete its volume to get clean start. This what message displayed on container's initialization is telling you:

> PostgreSQL Database directory appears to contain a database; Skipping initialization

**Comment by John-Theo** [comment]
Oh! Let me run `docker system prune --volumes` right away!

**Comment by John-Theo** [comment]
Now it works perfectly great! Thx!! @rafalp
